### PR TITLE
Add remove_cv_ref

### PR DESCRIPTION
**Pull request by pdimov**
This adds the new transformation trait remove_cv_ref, with the obvious semantics.

### CODE REVIEW

**Comment by jzmaddock** [comment]
Thanks, should we have the obvious make_const_reference as well?

**Comment by pdimov** [comment]
Not sure about that. I haven't come across a need for it, and the semantics aren't as obvious, because `add_const_reference<int&>` could legitimately be construed to mean either `int&` or `int const&`.

Realistically, the only reason for using `add_reference<T>` instead of `T&` is `void`, and there we also have a bit of a problem - `add_const_reference<void>` is `void const` or just `void`?

Might still be useful, we just need to clarify the behavior in those corner cases.

**Comment by viboes** [comment]
What was the feedback of  the proposed `uncvref` ?

**Comment by pdimov** [comment]
When I brought that up a few days ago, people raised a surprising (to me) amount of objections for such a small and obviously missing component. If only they were similarly diligent in screening other std:: proposals.

**Pull request merged**
