### PR TITLE
Implement detection idiom toolkit

### PR DESCRIPTION
**Pull request by glenfe**
Implements the Detection Idiom [N4502](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4502.pdf) adopted into <experimental/type_traits> into C++ standard Fundamentals TS v2.

Example usage: My `std::to_address` that was adopted for C++20 ([P0653R2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0653r2.html)) could be implemented conveniently as:
```
template<class T>
using __to_address_t = decltype(pointer_traits<T>::to_address(declval<const T&>()));

template<class T>
constexpr T* to_address(T* p) noexcept
{
    return p;
}

template<class T>
auto to_address(const T& p) noexcept
{
    if constexpr (is_detected_v<__to_address_t, T>) {
        return pointer_traits<T>::to_address(p);
    }  else {
        return std::to_address(p.operator->());
    }
}
```

### CODE REVIEW

**Comment by glenfe** [comment]
John, do you want each trait here to have its own QBK documentation page, or can I consolidate them all in one?

**Comment by jzmaddock** [comment]
Apologies for just catching up with this - at present I'm not really clear what these traits actually do - but normally, yes one page per trait.  In fact normally one header per trait as well...

**Comment by glenfe** [comment]
Will do.

**Comment by glenfe** [comment]
Updated the pull request: One header per trait, and one documentation page per trait.

> at present I'm not really clear what these traits actually do

I also updated the original comment of this pull request with a summary and example.

**Comment by jzmaddock** [comment]
I'm going to wait for the churn in the library to settle before merging this (ie clean CI).

Can I get you to link to the original paper in the docs?  Also some small examples illustrating the difference between the various traits would be very helpful.

Bloody clever idiom BTW :)

**Comment by glenfe** [comment]
> Can I get you to link to the original paper in the docs? Also some small examples illustrating the difference between the various traits would be very helpful.

Done (link) and somewhat-done (examples). :) Updated PR; Appveyor has cycled, just waiting on Travis.

**Comment by glenfe** [comment]
Travis and Appveyor confirmed Green (like Lantern).  Not Red (like Tornado).

**Comment by jzmaddock** [comment]
This is working very nicely with gcc, not so much with msvc, for example given:

```
template <class T>
using has_equal_to_func = decltype(std::declval<T>() == std::declval<T>());

template <class T>
using has_equal_to = boost::is_detected<has_equal_to_func, T>;
```

and

```
struct tester{};

static_assert(! ::has_equal_to<tester>::value);
```

Then msvc generates:

```
m:\data\boost\boost\t.cpp(15): error C2676: binary '==': 'tester' does not define this operator or a conversion to a type acceptable to the predefined operator
```

Annoyingly, msvc's intellisense does accept the code!

I'm not sure if there's anything we can do to fix this?

**Comment by glenfe** [comment]
Which version of MSVC? I'm guessing 2017 given the use of C++17 form of static_assert. Can you check how that version behaves with:
```cpp
#include <boost/type_traits/declval.hpp>
#include <boost/type_traits/integral_constant.hpp>
#include <boost/type_traits/make_void.hpp>

template<class, class = void>
struct has_equal_to
    : boost::false_type { };

template<class T>
struct has_equal_to<T,
    boost::void_t<decltype(boost::declval<T>() == boost::declval<T>())> >
    : boost::true_type { };

struct tester { };

static_assert(!has_equal_to<tester>::value, "et cetera");
```
If it is the usual MSVC expression-SFINAE support deficiency, I suspect there is not much we can do.

**Comment by jzmaddock** [comment]
Yep, so far as I can tell, direct use of the detection idiom works fine (including your code above), it's only when invoked via is_detected that it fails.

**Comment by glenfe** [comment]
In that case there might be some opportunity for MSVC-specific workarounds in the detection idiom. I'll see what I can do, tonight.

**Comment by glenfe** [comment]
Solution found: Pull request incoming.

**Pull request merged**
