### PR TITLE
Add enable_if_ and enable_if_t. Sever dependency on Core.

### PR DESCRIPTION
**Pull request by glenfe**
As discussed on the mailing list.

### CODE REVIEW

**Comment by jzmaddock** [comment]
Is this a good time to coordinate a merge to master?

**Comment by glenfe** [comment]
I think so.

**Comment by glenfe** [comment]
The changes in Core have been merged to master. You should be able to merge TypeTraits any time, so the sooner the better. :)

**Comment by jzmaddock** [comment]
Done- thanks!

**Pull request merged**
