### PR TITLE
Add failing test for non-default constructible pair

### PR DESCRIPTION
**Pull request by vinniefalco**
Reproduces #51

### CODE REVIEW

**Comment by vinniefalco** [comment]
@pdimov This reproduces the error described in https://github.com/boostorg/optional/issues/39

**Comment by pdimov** [comment]
The addition should be to `has_trivial_constr_test.cpp`, not here.

**Comment by pdimov** [comment]
Interesting that it passes though. I had similar trouble making it fail in https://github.com/boostorg/optional/pull/40.

**Comment by pdimov** [comment]
Ah, the reason it passed was that it caught the window in which Boost.Build was broken and didn't pass `-std=c++11` so everything was C++03. I've restarted it.

**Comment by pdimov** [comment]
Reproduces now (as in, fails compilation on g++ 4.9), but the test fails (the trait reports true) all over the place too, which is interesting.

**Comment by pdimov** [comment]
> The addition should be to has_trivial_constr_test.cpp, not here.

https://github.com/boostorg/type_traits/pull/53

Let's see if it reproduces.

**Comment by jzmaddock** [comment]
Closing as now fixed.

**Pull request closed without merging**
