### PR TITLE
Implement copy_reference and copy_cv_ref

### PR DESCRIPTION
**Pull request by glenfe**

### CODE REVIEW

**Comment by glenfe** [comment]
Peter wants one of these (copy_cv_ref) for Variant2.

**Comment by jzmaddock** [comment]
These look fine: my only comment is that they are inconsistently named, do we change to `copy_cv_reference` or to `copy_ref`?  Any precedent?

**Comment by glenfe** [comment]
Affirmative: remove_reference, remove_cv_ref.

**Comment by jzmaddock** [comment]
So leave the names as they are then?

**Comment by glenfe** [comment]
Yes. :)

**Comment by glenfe** [comment]
Thanks John.

**Pull request merged**
